teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 0
        target: linear.y
        scale: 0.3
        offset: 0.0
      -
        axis: 1
        target: linear.x
        scale: 0.3
        offset: 0.0
      -
        axis: 3
        target: angular.z
        scale: 0.5
  hello:
    type: topic
    message_type: std_msgs/String
    topic_name: chatter
    deadman_buttons: [1]
    message_value:
      -
        target: data
        value: 'Hello'
